#!/bin/sh
cd
echo
echo "Possible commands:"
echo
ls -1 git-shell-commands
echo "quit"
echo "exit"
echo
echo "WARNING:"
echo "This git service is intended for private code sharing only."
echo "Service is subject to down time, glitches or compromissing."
echo "You should be aware that any authorized user can clone, pull or push to any repos hosted here."
echo "Only administrator can remove repos."
echo "Please do not use this service as backup or private file storage."
echo "ABSOLUTELY NO SELFIES"
echo

