#!/bin/sh

cd

SELF=`basename $0`
BASE=`git-shell-commands/baseurl`

if [ -z "$1" ]
then
  echo "$SELF: add a git repository."
  echo
  echo "Usage:"
  echo "    $SELF name_of_repo"
  echo
  echo "\".git\" will be automatically appended."
  exit 1
fi

if [ -e "$1.git" ]
then
  echo "$1 already exists."
  exit 1
fi

mkdir "$1.git"
cd "$1.git"
git --bare init
rm -f hooks/*.sample
echo "$SELF: done."
echo "Your repo address: $BASE$1.git"

